In [1]:
import sklearn
import numpy as np
from sklearn import model_selection, datasets, metrics, tree, ensemble, naive_bayes

In [2]:
X1, y1 = datasets.load_digits(return_X_y = True)
X2, y2 = datasets.load_breast_cancer(return_X_y = True)

In [3]:
X1.shape

(1797, 64)

In [4]:
X2.shape

(569, 30)

In [5]:
#sklearn.model_selection.cross_val_score
#BernoulliNB, MultinomialNB и GaussianNB

In [6]:
clf_b1 = naive_bayes.BernoulliNB()
clf_b1.fit(X1, y1)
b1_arr = model_selection.cross_val_score(clf_b1, X1, y1)

F:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [7]:
print (np.mean(b1_arr))

0.8258236507780582


In [8]:
clf_b2 = naive_bayes.BernoulliNB()
clf_b2.fit(X2, y2)
b2_arr = model_selection.cross_val_score(clf_b2, X2, y2)

F:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [9]:
print (np.mean(b2_arr))

0.6274204028589994


In [10]:
clf_m1 = naive_bayes.MultinomialNB()
clf_m1.fit(X1, y1)
m1_arr = model_selection.cross_val_score(clf_m1, X1, y1)

F:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [11]:
print (np.mean(m1_arr))

0.8708771489735053


In [12]:
clf_m2 = naive_bayes.MultinomialNB()
clf_m2.fit(X2, y2)
m2_arr = model_selection.cross_val_score(clf_m2, X2, y2)

F:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [13]:
print (np.mean(m2_arr))

0.8945790401930752


In [14]:
clf_g1 = naive_bayes.GaussianNB()
clf_g1.fit(X1, y1)
g1_arr = model_selection.cross_val_score(clf_g1, X1, y1)

F:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [15]:
print (np.mean(g1_arr))

0.8186003803550138


In [16]:
clf_g2 = naive_bayes.GaussianNB()
clf_g2.fit(X2, y2)
g2_arr = model_selection.cross_val_score(clf_g2, X2, y2)

F:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [17]:
print (np.mean(g2_arr))

0.9367492806089297


In [18]:
def write_answer_1(ans):
    with open("task2_ans1.txt", "w") as fout:
        fout.write(str(ans))
        
def write_answer_2(ans):
    with open("task2_ans2.txt", "w") as fout:
        fout.write(str(ans))

In [19]:
write_answer_1(max([np.mean(b2_arr), np.mean(m2_arr), np.mean(g2_arr)]))

In [20]:
write_answer_2(max([np.mean(b1_arr), np.mean(m1_arr), np.mean(g1_arr)]))

In [33]:
def write_answer_3(features):
    with open("task2_ans3.txt", "w") as fout:
        fout.write(" ".join([str(num) for num in features]))

In [35]:
write_answer_3([3, 4])

In [28]:
X1[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [27]:
y1[:100]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 5, 5, 6, 5, 0, 9, 8, 9, 8, 4, 1, 7,
       7, 3, 5, 1, 0, 0, 2, 2, 7, 8, 2, 0, 1, 2, 6, 3, 3, 7, 3, 3, 4, 6,
       6, 6, 4, 9, 1, 5, 0, 9, 5, 2, 8, 2, 0, 0, 1, 7, 6, 3, 2, 1, 7, 4,
       6, 3, 1, 3, 9, 1, 7, 6, 8, 4, 3, 1])

In [29]:
X2[0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [31]:
y2[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])