In [1]:
import numpy as np
import pandas as pd
from sklearn.cluster import MeanShift

In [2]:
checkins = pd.read_csv('checkins.dat', sep='|', skipinitialspace=True, skiprows=[1], low_memory=False)
print(checkins.info())
checkins.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1021967 entries, 0 to 1021966
Data columns (total 6 columns):
id                  1021967 non-null object
user_id             1021966 non-null float64
venue_id            1021966 non-null float64
latitude            396634 non-null float64
longitude           396634 non-null float64
created_at          1021966 non-null object
dtypes: float64(4), object(2)
memory usage: 46.8+ MB
None


id       user_id   venue_id   latitude        longitude       \
0  984301   2041916.0     5222.0             NaN             NaN   
1  984222     15824.0     5222.0       38.895112      -77.036366   
2  984315   1764391.0     5222.0             NaN             NaN   
3  984234     44652.0     5222.0       33.800745      -84.410520   
4  984249   2146840.0     5222.0             NaN             NaN   

      created_at        
0  2012-04-21 17:39:01  
1  2012-04-21 17:43:47  
2  2012-04-21 17:37:18  
3  2012-04-21 17:43:43  
4  2012-04-21 17:42:58

In [5]:
checkins.columns = checkins.columns.str.strip()

In [10]:
checkins = checkins.dropna()
print(checkins.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 396634 entries, 1 to 1021964
Data columns (total 6 columns):
id            396634 non-null object
user_id       396634 non-null float64
venue_id      396634 non-null float64
latitude      396634 non-null float64
longitude     396634 non-null float64
created_at    396634 non-null object
dtypes: float64(4), object(2)
memory usage: 21.2+ MB
None


In [11]:
checkins = checkins.head(n = 100000)
print(checkins.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 1 to 233798
Data columns (total 6 columns):
id            100000 non-null object
user_id       100000 non-null float64
venue_id      100000 non-null float64
latitude      100000 non-null float64
longitude     100000 non-null float64
created_at    100000 non-null object
dtypes: float64(4), object(2)
memory usage: 5.3+ MB
None


In [14]:
offices = pd.read_csv('t1_offices.txt', skipinitialspace=True)
print(offices.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
latitude     6 non-null float64
longitude    6 non-null float64
city         6 non-null object
dtypes: float64(2), object(1)
memory usage: 224.0+ bytes
None


In [15]:
offices_for_dist = offices.loc[:, ['latitude', 'longitude']]
checkins_for_dist = checkins.loc[:, ['latitude', 'longitude']]

In [18]:
checkins_for_dist

latitude   longitude
1       38.895112  -77.036366
3       33.800745  -84.410520
7       45.523452 -122.676207
9       40.764462 -111.904565
10      33.448377 -112.074037
11      32.221743 -110.926479
12      40.650000  -73.950000
13      33.448377 -112.074037
15      33.414768 -111.909309
18      42.358431  -71.059773
19      33.448377 -112.074037
20      33.414768 -111.909309
25      33.448377 -112.074037
26      33.248664 -111.634299
27      32.840678 -117.258794
29      34.052234 -118.243685
34      33.414768 -111.909309
35      33.448377 -112.074037
38      34.483901 -114.322455
40      34.048928 -111.093731
41      32.715329 -117.157255
42      33.448377 -112.074037
46      38.895112  -77.036366
47      33.745851 -117.826166
49      34.096111 -118.105833
50      34.052234 -118.243685
52      37.629349 -122.400087
53       4.598056  -74.075833
54      33.804167 -118.158056
55      40.735657  -74.172367
...           ...         ...
233728  32.678109 -117.099197
233730  34.019454 -118.491191
233731  37.339386 -121.894955
233732  40.650000  -73.950000
233735  43.009703  -85.520024
233736  34.746481  -92.289595
233737  41.763711  -72.685093
233738  44.310000  -96.790000
233739  35.221997 -101.831297
233741  40.740389  -73.983385
233742  33.641132 -117.918669
233743  40.715972  -74.001437
233744  41.033986  -73.762910
233746  27.937801  -82.285925
233749  36.087708  -86.648397
233751  26.203407  -98.230012
233753  40.740389  -73.983385
233755  40.768433  -73.525125
233758  42.866680  -88.333427
233759  40.704824  -73.650130
233761  43.652500  -79.381667
233765  42.372640  -71.109653
233769  35.994033  -78.898619
233780  29.762884  -95.383061
233787  41.878114  -87.629798
233788  33.575000 -117.725556
233789  37.629349 -122.400087
233793  29.762884  -95.383061
233797  32.802955  -96.769923
233798  37.774929 -122.419415

[100000 rows x 2 columns]

In [20]:
X = checkins_for_dist.to_numpy()

In [21]:
X

array([[  38.8951118,  -77.0363658],
       [  33.800745 ,  -84.41052  ],
       [  45.5234515, -122.6762071],
       ...,
       [  29.7628844,  -95.3830615],
       [  32.802955 ,  -96.769923 ],
       [  37.7749295, -122.4194155]])

In [22]:
cls = MeanShift(bandwidth = 0.1)
cls.fit(X)

MeanShift(bandwidth=0.1, bin_seeding=False, cluster_all=True, min_bin_freq=1,
     n_jobs=None, seeds=None)

In [27]:
cls.cluster_centers_.shape

(3231, 2)

In [30]:
answers = cls.labels_

In [33]:
len_label = cls.cluster_centers_.shape[0]
nums_label = np.zeros(len_label)

In [35]:
 for i in np.arange(len(answers)): #100000
    nums_label[answers[i]] += 1 

In [68]:
rasstrel = []

for i in np.arange(len(nums_label)):
    if nums_label[answers[i]] <= 15:
        rasstrel.append(i)

In [69]:
coordinates = cls.cluster_centers_

coordinates.shape

(3231, 2)

In [70]:
coordinates_purified = []

for i in np.arange(coordinates.shape[0]):
    if i not in rasstrel:
        coordinates_purified.append(coordinates[i])

In [71]:
coordinates

array([[  40.7177164 ,  -73.99183542],
       [  33.44943805, -112.00213969],
       [  33.44638027, -111.90188756],
       ...,
       [ -37.8229826 ,  145.1811902 ],
       [ -41.2924945 ,  174.7732353 ],
       [ -45.0311622 ,  168.6626435 ]])

In [72]:
coordinates_purified = np.stack(coordinates_purified)
coordinates_purified

array([[  40.7177164 ,  -73.99183542],
       [  33.44943805, -112.00213969],
       [  33.44638027, -111.90188756],
       ...,
       [ -37.7133771 ,  145.1489162 ],
       [ -37.8229826 ,  145.1811902 ],
       [ -45.0311622 ,  168.6626435 ]])

In [83]:
def get_dist(coordinates_purified, offices): #не надо говорить, до какого офиса дистанция 
    dist = []
    for elem1 in coordinates_purified:
        d_temp = []
        for elem2 in offices:
            dist2 = (elem1[0] - elem2[0]) ** 2 + (elem1[1] - elem2[1]) ** 2 #?
            d_temp.append(dist2)
        dist.append(np.min(d_temp))
    return dist      

In [93]:
arr_dist = get_dist(coordinates_purified, offices_for_dist.to_numpy())

In [94]:
arr_dist

[260.6196951446073,
 38.36513014513654,
 39.61747559136554,
 309.71001165463304,
 33.316537881494334,
 180.20730333587142,
 40.68223235481678,
 78.95079528601653,
 357.6713729464592,
 209.12709704747704,
 14.704041114028657,
 0.09915180141653804,
 532.726230792179,
 322.77681464955947,
 264.11437784778195,
 210.11189380885284,
 224.99733339176464,
 0.1434042236031941,
 1.8269721938729662,
 318.5618985917373,
 27.06216666772045,
 8.267083116801127,
 2.15289434402374,
 55.07918481112856,
 0.16808605549613967,
 241.92004518533867,
 352.51633802876626,
 28.4410976290345,
 0.01798523282924829,
 158.72285819368048,
 34.54534161804904,
 0.11479253475179307,
 8.917216300697644,
 0.16844288870139407,
 378.3950876777026,
 317.20028059526726,
 32.96384911033559,
 206.79147922138208,
 227.266970438418,
 0.04486370350982694,
 208.8816606065793,
 193.8165211161353,
 50.427747468398316,
 0.14954170433211428,
 259.57495361174745,
 31.304107671855665,
 0.20075356588691057,
 0.005019401190076088,
 266.8

In [95]:
ans_arg = np.argmin(arr_dist)

In [96]:
np.min(arr_dist)

6.138343547440554e-05

In [97]:
def write_answer(features):
    with open("task1_ans.txt", "w") as fout:
        fout.write(" ".join([str(num) for num in features]))

In [98]:
write_answer(coordinates_purified[ans_arg])